# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dunfell branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a build.
        run: |
          set -x
          REPO=$(basename $GITHUB_REPOSITORY)
          BRANCH=$(echo $GITHUB_REF | sed s,refs/heads/,,)
          TOPDIR=$(pwd)
          rm -rf $REPO-$BRANCH
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $REPO-$BRANCH
          pushd $REPO-$BRANCH
          git checkout $BRANCH
          popd
          rm -rf project-$BRANCH/tmp
          bash $REPO-$BRANCH/setup.sh project-$BRANCH
          source project-$BRANCH/setup.sh
          echo "INHERIT+='rm_work'" > conf/site.conf 
          echo "SSTATE_DIR='$TOPDIR/sstate-cache'" >> conf/site.conf 
          echo "DL_DIR='$TOPDIR/downloads'" >> conf/site.conf 
          bitbake -k default-sdk 
